services:
  arbitr1:
    build: .
    environment:
      CHAIN: "BTC->XMR->USDT"
    volumes:
      - ./share:/app/share
    restart: "no"


  arbitr2:
    build: .
    environment:
      CHAIN: "USDT->XMR->BTC"
    volumes:
      - ./share:/app/share
    restart: "no"
    depends_on:
      - arbitr1

  arbitr3:
    build: .
    environment:
      CHAIN: "BTC->BNB->USDT"
    volumes:
      - ./share:/app/share
    restart: "no"
    depends_on:
      - arbitr2

  arbitr4:
    build: .
    environment:
      CHAIN: "BTC->BNB->USDC"
    volumes:
      - ./share:/app/share
    restart: "no"
    depends_on:
      - arbitr3

